theme: jekyll-theme-slate
title: Welcome to the Lavlesh's Homepage!
description: You can bookmark this for intersting information about ServiceNow
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
